declare module '@editorjs/list'
declare module '@editorjs/code'
declare module '@editorjs/paragraph'
declare module '@editorjs/header'
declare module '@editorjs/quote'
declare module '@editorjs/link'
declare module '@editorjs/image'
